services:
    keycloak-service:
        image: quay.io/keycloak/keycloak:latest
        ports:
            - "8080:8080"
        environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
        networks:
            - services-network
        volumes:
          - ./realms:/opt/keycloak/data/import
        command: ["start-dev", "--import-realm"]

    postgres-db:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: AccountServiceDB
        ports:
           - "5432:5432"
        networks:
            - services-network
        volumes:
            - postgres_data:/var/lib/postgresql/data 
    
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"  
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - services-network
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq 

    account-service:
        build:
            context: .
            dockerfile: AccountService/Dockerfile
        ports:
            - "80:80"
        networks:
            - services-network
        depends_on:
            - keycloak-service
            - postgres-db
            - rabbitmq 
  
networks:
    services-network:    
        driver: bridge

volumes:
    postgres_data:
    rabbitmq_data:
