services:
    keycloak-service:
        image: quay.io/keycloak/keycloak:latest
        ports:
            - "8080:8080"
        environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
        networks:
            - services-network
        volumes:
          - ./realms:/opt/keycloak/data/import
        command: ["start-dev", "--import-realm"]

    postgres-db:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: AccountServiceDB
        ports:
           - 5432:5432
        networks:
            - services-network

    account-service:
        build:
            context: .
            dockerfile: AccountService/Dockerfile
        ports:
            - "5080:80"
        networks:
            - services-network
        depends_on:
            - keycloak-service
            - postgres-db
  
networks:
    services-network:    
        driver: bridge
